package controller;

public enum ActionsUser {
	VIEW_USER_FAVORITES,OPT_USER_VIEW_PRODUCTS,SHOPPING_CAR_USER,SHOW_PRODUCTS_BY_SHOP,
	BACK_TO_PANEL_RESTAURANTS,USER_SETTINGS,LOG_OUT,SEARCH_RESTAURANT,CANCEL_PRODUCT,
	CHANGE_TO_PRODUCTS_FROM_SHOP_PANEL,	USER_VIEW,	SHOW_EDIT_USER,CONFIRM,ADD_IMAGE_TO_USER,
	EDIT_USER,ADD_USER
}
