package controller;

public enum Actions {
	ADD_USER, SHOW_DROP_DOWN_MENU, SEARCH_RESTAURANT, CHARGE_IMAGE, ADD_PRODUCT, CANCEL_PRODUCT,
	ADD_SHOP, ADD_IMAGE_TO_SHOP, SHOW_ADD_SHOP_DIALOG, SHOW_ADD_USER_DIALOG, ADD_IMAGE_TO_USER,
	SHOW_ADD_PRODUCT, CHARGE_IMAGE_PRODUCT, GO_LEFT_ARROW, GO_RIGHT_ARROW, DELETE_PRODUCT, DELETE_SHOP,
	DELETE_USER,EDIT_PRODUCT, EDIT_SHOP, EDIT_USER, CHANGE_TO_PRODUCTS_FROM_SHOP_PANEL, USER_LOG_IN, 
	OPEN_DIALOG_LOG_IN, SHOP_LOG_IN, ADMIN_VIEW, USER_VIEW, SHOP_VIEW, SHOW_ADD_PRODUCT_FROM_SHOP_VIEW_DIALOG, 
	SHOW_EDIT_PRODUCT, SHOW_EDIT_USER, SHOW_PRODUCTS_BY_SHOP, SHOW_EDIT_SHOP, CONFIRM, ADD_PRODUCT_TO_SHOP, EDIT_PRODUCT_TO_SHOP,
	CHARGE_IMAGE_PRODUCT_FROM_SHOP_VIEW, VIEW_USER_FAVORITES, OPT_USER_VIEW_PRODUCTS, USER_SETTINGS,
	SHOPPING_CAR_USER, OPEN_DIALOG_CHOOSE, BACK_TO_PANEL_RESTAURANTS, LOG_OUT
}