package controller;

public enum ActionsAdmin {
	ADD_USER, SHOW_DROP_DOWN_MENU, CHARGE_IMAGE, ADD_PRODUCT, 
	ADD_IMAGE_TO_SHOP, SHOW_ADD_SHOP_DIALOG, SHOW_ADD_USER_DIALOG, ADD_IMAGE_TO_USER,
	SHOW_ADD_PRODUCT, CHARGE_IMAGE_PRODUCT, GO_LEFT_ARROW, GO_RIGHT_ARROW,
	DELETE_PRODUCT, DELETE_SHOP,DELETE_USER,EDIT_PRODUCT, EDIT_SHOP, EDIT_USER, USER_LOG_IN, 
	OPEN_DIALOG_LOG_IN, SHOP_LOG_IN, ADMIN_VIEW, SHOW_EDIT_PRODUCT, 
	SHOW_EDIT_USER,SHOW_EDIT_SHOP, EDIT_PRODUCT_TO_SHOP,
	OPEN_DIALOG_CHOOSE, LOG_OUT,ADD_SHOP,CANCEL_PRODUCT,CONFIRM
}