package controller;

public enum ActionsAdmin {
	ADD_USER, ADD_PRODUCT,ADD_IMAGE_TO_SHOP,
	SHOW_ADD_SHOP_DIALOG, SHOW_ADD_USER_DIALOG, ADD_IMAGE_TO_USER,
	SHOW_ADD_PRODUCT_DIALOG, CHARGE_IMAGE_PRODUCT, GO_LEFT_ARROW, GO_RIGHT_ARROW,
	DELETE_PRODUCT, DELETE_SHOP,DELETE_USER,EDIT_PRODUCT, EDIT_SHOP, EDIT_USER,  
	SHOW_EDIT_PRODUCT, SHOW_EDIT_USER,SHOW_EDIT_SHOP, EDIT_PRODUCT_TO_SHOP,
	LOG_OUT,ADD_SHOP,CANCEL_PRODUCT,
}